# Generated by Django 2.2.1 on 2019-07-15 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customergroups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=20)),
                ('print_l', models.DecimalField(decimal_places=2, default=29.7, max_digits=19)),
                ('print_b', models.DecimalField(decimal_places=2, default=21, max_digits=19)),
                ('paper_l', models.DecimalField(decimal_places=2, default=29.7, max_digits=19)),
                ('paper_b', models.DecimalField(decimal_places=2, default=21, max_digits=19)),
                ('sheet_count', models.DecimalField(decimal_places=2, default=21, max_digits=19)),
                ('gsm', models.DecimalField(decimal_places=2, default=100, max_digits=19)),
                ('print_opt', models.CharField(max_length=20)),
                ('color_opt', models.CharField(max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customergroups.CustomerGroup')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
    ]
